name: flutter_ui_challenges
description: "Flutter UI Challenges."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_gen: ^5.10.0
  flutter_svg: ^2.2.2
  google_fonts: ^6.2.1
  salomon_bottom_bar: ^3.3.2
  carousel_slider: ^5.0.0
  animate_do: ^4.2.0
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  intl: ^0.20.2
  bloc: ^9.1.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_gen_runner:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_gen:
  output: lib/utils/gen/
  line_length: 80

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/coffee_app/
    - assets/icons/